spring:
  application:
    name: atlasstay-backend
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/AtlasStay
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: "/api/v1"


#  logging:
#    level:
#      root: INFO
#      com.yourpackage: DEBUG
#
#    pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

kind: Application
vendorUrl:
description:
title:
vendorName:
config:
url:
